notifications:
  email:
    on_success: never
    on_failure: never

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

sudo: required
dist: trusty
os:
  - linux
addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - ocl-icd-opencl-dev

before_install:
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty multiverse"
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-updates main restricted"
    - sudo apt-get update -qq
    - sudo apt-get install -qq fglrx


env:
  global:
    - APM_TEST_PACKAGES="linter language-opencl"

  matrix:
    - ATOM_CHANNEL=stable

before_script:
    - pip install pyopencl
    - python /home/travis/build/BenSolus/linter-opencl/lib/clCompiler.py -p
