notifications:
  email:
    on_success: never
    on_failure: never

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

sudo: true

os:
  - linux

before_install:
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty multiverse"
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty universe"
    - sudo add-apt-repository "deb-src http://archive.ubuntu.com/ubuntu trusty universe"
    - sudo apt-get -qq update
    - python /home/travis/build/BenSolus/linter-opencl/lib/clCompiler.py -p
env:
  global:
    - APM_TEST_PACKAGES="linter language-opencl"

  matrix:
    - ATOM_CHANNEL=stable

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - ocl-icd-libopencl1
    - python-pyopencl
