### Project specific config ###
language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      env: ATOM_CHANNEL=stable

    - os: osx
      env: ATOM_CHANNEL=stable

### Generic setup follows ###
script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

# before_install:
#     - bash .travis/amd_sdk.sh;
#     - tar -xjf AMD-SDK.tar.bz2;
#     - AMDAPPSDKROOT=${HOME}/AMDAPPSDK;
#     - export OPENCL_VENDOR_PATH=${AMDAPPSDKROOT}/etc/OpenCL/vendors;
#     - mkdir -p ${OPENCL_VENDOR_PATH};
#     - sh AMD-APP-SDK*.sh --tar -xf -C ${AMDAPPSDKROOT};
#     - echo libamdocl64.so > ${OPENCL_VENDOR_PATH}/amdocl64.icd;
#     - export LD_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64:${LD_LIBRARY_PATH};
#     - export CMAKE_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64;
#     - export LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64:${LIBRARY_PATH};

notifications:
  email:
    on_success: never
    on_failure: change

env:
  global:
    - APM_TEST_PACKAGES="linter"

branches:
  only:
    - master

git:
  depth: 10

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - opencl-headers
    - pocl
