notifications:
  email:
    on_success: never
    on_failure: never

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

sudo: true

os:
  - linux

before_install:
    - apm install language-opencl
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty multiverse"
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-updates multiverse"
env:
  global:
    - APM_TEST_PACKAGES=""

  matrix:
    - ATOM_CHANNEL=stable

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - opencl-headers
    - python-pyopencl
