notifications:
  email:
    on_success: never
    on_failure: change

matrix:
  include:
    - os: linux
      env: ATOM_CHANNEL=stable

    - os: osx
      env: ATOM_CHANNEL=stable

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

before_install:
    - bash .travis/amd_sdk.sh;
    - tar -xjf AMD-SDK.tar.bz2;
    - AMDAPPSDKROOT=${HOME}/AMDAPPSDK;
    - export OPENCL_VENDOR_PATH=${AMDAPPSDKROOT}/etc/OpenCL/vendors;
    - mkdir -p ${OPENCL_VENDOR_PATH};
    - sh AMD-APP-SDK*.sh --tar -xf -C ${AMDAPPSDKROOT};
    - echo libamdocl64.so > ${OPENCL_VENDOR_PATH}/amdocl64.icd;
    - export LD_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64:${LD_LIBRARY_PATH};
    - export CMAKE_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64;
    - chmod +x ${AMDAPPSDKROOT}/bin/x86_64/clinfo;
    - ${AMDAPPSDKROOT}/bin/x86_64/clinfo;
    - export LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64:${LIBRARY_PATH};

env:
  global:
    - APM_TEST_PACKAGES="linter"

branches:
  only:
    - master

git:
  depth: 10

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - opencl-headers
