notifications:
  email:
    on_success: never
    on_failure: never

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

sudo: required
dist: trusty
os:
  - linux

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq opencl-headers
    - bash .travis/amd_sdk.sh;
    - tar -xjf AMD-SDK.tar.bz2;
    - AMDAPPSDKROOT=/usr
    #- AMDAPPSDKROOT=${HOME}/AMDAPPSDK;
    - export OPENCL_VENDOR_PATH=${AMDAPPSDKROOT}/etc/OpenCL/vendors;
    - sudo mkdir -p ${OPENCL_VENDOR_PATH};
    - sudo sh AMD-APP-SDK*.sh --tar -xf -C ${AMDAPPSDKROOT};
    - sudo echo libamdocl64.so | sudo tee --append ${OPENCL_VENDOR_PATH}/amdocl64.icd;
    - export LD_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64:${LD_LIBRARY_PATH};
    - export CMAKE_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64;
    - sudo chmod +x ${AMDAPPSDKROOT}/bin/x86_64/clinfo;
    - ${AMDAPPSDKROOT}/bin/x86_64/clinfo;
    - sudo >&2 ldconfig -v


env:
  global:
    - APM_TEST_PACKAGES="linter language-opencl"

  matrix:
    - ATOM_CHANNEL=stable

before_script:
    - pip install pyopencl
    - python /home/travis/build/BenSolus/linter-opencl/lib/clCompiler.py -p
